name: Docker Image Build Test

on:
  push:
    branches: 
    - Dev
    - master
  pull_request:
    branches: [ "Dev" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . -t pizza-template -f Dockerfile

    - name: Send Notification ntfy
      run: |
        curl \
        -H "Title: Pizza Template Successfully Built" \
        -H "Priority: default" \
        -H "Tags: green_circle,pizza" \
        -d "The Github action has been successfull." \
        https://notify.rp-helpdesk.com/Github
