name: Docker Image Build Test

on:
  push:
    branches: 
    - Dev
  pull_request:
    branches: [ "Dev" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . -t palermo:dev -f Dockerfile
        docker tag palermo:dev 192.168.1.140:5000/palermo:dev
        docker push 192.168.1.140:5000/palermo:dev

    - name: ntfy-failed-notifications
      uses: niniyas/ntfy-action@master
      if: failure()
      with:
        url: '${{ secrets.NTFYURL }}'
        topic: '${{ secrets.NTFYTOPIC }}'
        priority: 5
        tags: +1,partying_face,action,failed
        details: Workflow has failed!
  
    - name: ntfy-success-notifications
      uses: niniyas/ntfy-action@master
      if: success()
      with:
        url: '${{ secrets.NTFYURL }}'
        topic: '${{ secrets.NTFYTOPIC }}'
        priority: 3
        tags: +1,partying_face,action,successfully,completed
        details: Workflow has been successfully completed!
  
    - name: ntfy-cancelled-notifications
      uses: niniyas/ntfy-action@master
      if: cancelled()
      with:
        url: '${{ secrets.NTFYURL }}'
        topic: '${{ secrets.NTFYTOPIC }}'
        priority: 3
        tags: +1,partying_face,action,cancelled
        details: Workflow has been cancelled!