name: Snyk Security
on: push
jobs:
  security:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@4
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/nodemaster
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_API_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif

      - name: ntfy-failed-notifications
        uses: niniyas/ntfy-action@master
        if: failure()
        with:
          url: '${{ secrets.NTFYURL }}'
          topic: '${{ secrets.NTFYTOPIC }}'
          priority: 5
          tags: +1,partying_face,action,failed
          details: Workflow has failed!

      - name: ntfy-success-notifications
        uses: niniyas/ntfy-action@master
        if: success()
        with:
          url: '${{ secrets.NTFYURL }}'
          topic: '${{ secrets.NTFYTOPIC }}'
          priority: 3
          tags: +1,partying_face,action,successfully,completed
          details: Workflow has been successfully completed!

      - name: ntfy-cancelled-notifications
        uses: niniyas/ntfy-action@master
        if: cancelled()
        with:
          url: '${{ secrets.NTFYURL }}'
          topic: '${{ secrets.NTFYTOPIC }}'
          priority: 3
          tags: +1,partying_face,action,cancelled
          details: Workflow has been cancelled!