name: Synk CLI Test
on: 
  push:
     branches:
        - Dev # Modify this to your branch name
jobs:
  security:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_API_TOKEN }}
        with:
          command: monitor
