name: Synk CLI Test
on: 
  push:
     branches:
        - Dev # Modify this to your branch name
jobs:
  security:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_API_TOKEN }}
        with:
          command: monitor
          - name: ntfy-failed-notifications
          uses: niniyas/ntfy-action@master
          if: failure()
          with:
            url: '${{ secrets.NTFYURL }}'
            topic: '${{ secrets.NTFYTOPIC }}'
            priority: 5
            tags: +1,partying_face,action,failed
            details: Workflow has failed!
    
          - name: ntfy-success-notifications
            uses: niniyas/ntfy-action@master
            if: success()
            with:
              url: '${{ secrets.NTFYURL }}'
              topic: '${{ secrets.NTFYTOPIC }}'
              priority: 3
              tags: +1,partying_face,action,successfully,completed
              details: Workflow has been successfully completed!
    
          - name: ntfy-cancelled-notifications
            uses: niniyas/ntfy-action@master
            if: cancelled()
            with:
              url: '${{ secrets.NTFYURL }}'
              topic: '${{ secrets.NTFYTOPIC }}'
              priority: 3
              tags: +1,partying_face,action,cancelled
              details: Workflow has been cancelled!